import assert from "node:assert";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const firebaseInit = fs.readFileSync(path.join(root, "firebase-init.js"), "utf8");
const login = fs.readFileSync(path.join(root, "login.html"), "utf8");
const calendar = fs.readFileSync(path.join(root, "calendar.js"), "utf8");
const calendarHtml = fs.readFileSync(path.join(root, "calendar.html"), "utf8");
const buildInfoGenerator = fs.readFileSync(path.join(root, "scripts", "generate-build-info.js"), "utf8");
const statusFunction = fs.readFileSync(path.join(root, "netlify", "functions", "google-calendar-status.js"), "utf8");
const eventsFunction = fs.readFileSync(path.join(root, "netlify", "functions", "google-calendar-events.js"), "utf8");
const eventsCore = fs.readFileSync(path.join(root, "netlify", "functions", "lib", "google-calendar-events.js"), "utf8");
const serviceWorker = fs.readFileSync(path.join(root, "service-worker.js"), "utf8");

assert.ok(firebaseInit.includes("export const googleProvider = new GoogleAuthProvider();"));
assert.ok(!firebaseInit.includes("googleProvider.addScope"));
assert.ok(!firebaseInit.includes("calendar.events.readonly"));
assert.ok(!login.includes("credentialFromResult"));
assert.ok(calendar.includes('"/.netlify/functions/google-calendar-oauth-start"'));
assert.ok(calendar.includes('"/.netlify/functions/google-calendar-status"'));
assert.ok(calendar.includes('"/.netlify/functions/google-calendar-events"'));
assert.ok(calendar.includes('status.connectionStatus === "connected"'));
assert.ok(calendar.includes('status.connectionStatus === "reconnect_required"'));
assert.ok(!calendar.includes('status.status === "connected"'));
assert.ok(statusFunction.includes('connectionStatus: usable ? "connected" : "reconnect_required"'));
assert.ok(!statusFunction.includes('return { status:'));
assert.ok(!calendar.includes("calendar/v3"));
assert.ok(!calendar.includes("events.list"));
assert.ok(calendar.includes("JSON.stringify(payload)"));
assert.ok(calendar.includes('Google Calendar · ${esc(event.summary || "Untitled event")}'));
assert.ok(calendar.includes('item.source === "google"'));
assert.ok(calendar.includes("monthLoadVersion"));
assert.ok(calendar.includes('authorizationUrl.origin !== "https://accounts.google.com"'));
assert.ok(calendarHtml.includes("Connect Google Calendar"));
assert.ok(calendarHtml.includes("READ ONLY"));
assert.ok(calendarHtml.includes("connected Google Calendar events"));
assert.ok(eventsCore.includes('/calendar/v3/calendars/primary/events'));
assert.ok(eventsCore.includes('url.searchParams.set("singleEvents", "true")'));
assert.ok(eventsCore.includes('url.searchParams.set("orderBy", "startTime")'));
assert.ok(eventsCore.includes("MAX_RETURNED_EVENTS"));
assert.ok(eventsFunction.includes("authenticateFirebaseUser(event, deps, responseHeaders)"));
assert.ok(eventsFunction.includes("doc(uid)"));
assert.ok(!eventsFunction.includes("atlas-context"));
assert.ok(!eventsFunction.includes("events.insert"));
assert.ok(!eventsFunction.includes("events.update"));
assert.ok(!eventsFunction.includes("events.delete"));
assert.ok(serviceWorker.includes('const CACHE = "eden-shell-v45"'));
assert.ok(serviceWorker.includes('"calendar.js"'));
assert.ok(serviceWorker.includes('const NEVER_CACHE_PATH_PREFIXES = ["/.netlify/functions/"]'));
assert.ok(!buildInfoGenerator.includes("GOOGLE_CALENDAR_CLIENT_SECRET"));
assert.ok(!buildInfoGenerator.includes("GOOGLE_CALENDAR_TOKEN_ENCRYPTION_KEY"));

console.log("google-calendar-ui.test.js: 38 assertions passed");
